name: adham_ai
description: "Adham Generative AI Web Application"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  animated_splash_screen: ^1.3.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_markdown: ^0.7.3
  flutter_native_splash: ^2.4.1
  flutter_tts: ^4.0.2
  google_generative_ai: ^0.4.3
  lottie: ^3.1.2
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Adham
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
    - family: Poppinss
      fonts:
        - asset: assets/fonts/Poppins-ExtraLight.ttf
  assets:
    - assets/hello.json
    

flutter_icons:
  android: true
  ios: true
  image_path : 'assets/logo.png'
  adaptive_icon_background: '#ffffff'